"""OSAHR: open stochastic adaptive hypergraph rewriting."""

from .adaptive import (
    AdaptiveParameter,
    AdaptiveRegistry,
    ConstraintPolicy,
    EligibilityTrace,
    ExponentialTrace,
    ParameterConstraint,
    ParameterScope,
    RobbinsMonro,
)
from .analysis import (
    EnsembleResult,
    EnsembleSample,
    PathLikelihood,
    path_log_likelihood,
    run_ensemble,
)
from .boundary import (
    BoundaryDirection,
    BoundaryHandle,
    BoundaryState,
    ExternalEvent,
    InputMode,
    OutputEvent,
)
from .causal import CausalTrace, EventFootprint
from .composition import CompositionResult, Wire, compose_structural
from .events import EventKind, EventRecord, StepResult, StepStatus
from .expr import Expr
from .graph import GraphDelta, Hyperedge, Hypergraph, Incidence, Side, Vertex
from .ids import EntityId
from .incremental import IncrementalMatcher, MatchDelta, RuleDependencySignature, RuleMatchCache
from .matcher import Match, Matcher
from .meta import (
    MetaParameter,
    MetaRuleAction,
    MetaRuleEvent,
    MetaValueKind,
    RuleTemplate,
)
from .observables import AttributeSum, EdgeCount, EntityCount
from .occurrence import Occurrence, OccurrenceDelta, OccurrenceIndex, OccurrenceKey
from .pattern import (
    ANY,
    BoundaryEffect,
    BoundaryEffectKind,
    ConditionPolarity,
    GraphCondition,
    OutputSpec,
    PatternEdge,
    PatternGraph,
    PatternVertex,
    Rule,
    StateAssignment,
    TemplateEdge,
    TemplateGraph,
    TemplateVertex,
    Var,
)
from .persistence import export_audit_log, load_checkpoint, save_checkpoint
from .runtime import (
    Model,
    Runtime,
    RuntimeConfig,
    RuntimeSnapshot,
    ScheduledAdaptation,
)
from .schema import (
    AttributeSpec,
    HyperedgeType,
    PortSpec,
    Schema,
    ValueKind,
    VertexType,
)
from .schedulers import NextReactionScheduler, SchedulerKind
from .weighted import FenwickTree, WeightedIndex, WeightedSelection

__all__ = [
    "ANY",
    "AdaptiveParameter",
    "AdaptiveRegistry",
    "AttributeSpec",
    "AttributeSum",
    "BoundaryDirection",
    "BoundaryEffect",
    "BoundaryEffectKind",
    "BoundaryHandle",
    "BoundaryState",
    "CausalTrace",
    "CompositionResult",
    "ConditionPolarity",
    "ConstraintPolicy",
    "EdgeCount",
    "EligibilityTrace",
    "EnsembleResult",
    "EnsembleSample",
    "EntityCount",
    "EntityId",
    "EventFootprint",
    "EventKind",
    "EventRecord",
    "Expr",
    "ExponentialTrace",
    "ExternalEvent",
    "FenwickTree",
    "GraphCondition",
    "GraphDelta",
    "Hyperedge",
    "HyperedgeType",
    "Hypergraph",
    "Incidence",
    "IncrementalMatcher",
    "InputMode",
    "Match",
    "Matcher",
    "MatchDelta",
    "MetaParameter",
    "MetaRuleAction",
    "MetaRuleEvent",
    "MetaValueKind",
    "Model",
    "NextReactionScheduler",
    "Occurrence",
    "OccurrenceDelta",
    "OccurrenceIndex",
    "OccurrenceKey",
    "OutputEvent",
    "OutputSpec",
    "ParameterConstraint",
    "ParameterScope",
    "PathLikelihood",
    "PatternEdge",
    "PatternGraph",
    "PatternVertex",
    "PortSpec",
    "RobbinsMonro",
    "Rule",
    "RuleDependencySignature",
    "RuleMatchCache",
    "RuleTemplate",
    "Runtime",
    "RuntimeConfig",
    "RuntimeSnapshot",
    "ScheduledAdaptation",
    "SchedulerKind",
    "Schema",
    "Side",
    "StateAssignment",
    "StepResult",
    "StepStatus",
    "TemplateEdge",
    "TemplateGraph",
    "TemplateVertex",
    "ValueKind",
    "Var",
    "Vertex",
    "VertexType",
    "WeightedIndex",
    "WeightedSelection",
    "Wire",
    "compose_structural",
    "export_audit_log",
    "load_checkpoint",
    "path_log_likelihood",
    "run_ensemble",
    "save_checkpoint",
]
